# Generated by Django 3.2.3 on 2021-05-25 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_addded',
            new_name='date_added',
        ),
    ]
