# Generated by Django 3.2.3 on 2021-05-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_profileuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
